export const SCHEMA_VERSION = 1
export const CYCLE_LENGTH = 1500
export const LOAN = 5000
export const STARTING_CASH = 500
export const WORK_PER_RATING = 100      // design anchor
export const THREAT_BASE_PER_RATING = 5 // design anchor
export const THREAT_CAP = 18            // design anchor
export const CONSEQUENCE_SPREAD = 2
export const HP_BASE = 15
export const HP_PER_RANK = 5
export const HIRE_COST_PER_RANK_SQ = 100
export const PAYOUT_PER_RATING_SQ = 150
export const STARTING_ROSTER_SLOTS = 3
export const MAX_ROSTER_SLOTS = 6
export const SLOT_PRICES = [300, 600, 1000] // 4th, 5th, 6th
export const STARTING_SEATS = 2
export const MAX_SEATS = 3
export const SEAT_PRICE = 250
export const OFFER_ARRIVAL_MIN = 40
export const OFFER_ARRIVAL_MAX = 60
export const OFFER_TTL_MIN = 60
export const OFFER_TTL_MAX = 90
export const CANDIDATE_CHANCE = 0.3     // else the offer is a job
export const MEDKIT = { price: 100, heal: 10 }
export const SUPPRESSOR = { price: 150, reduce: 9 }
export const STIM = { price: 150, multiplier: 1.5, duration: 10 }
export const REINFORCE_TRAVEL = 5
export const SUPPLY_TRAVEL = 3
export const BOND_THRESHOLDS = [2, 5, 9] // missions together for levels 1/2/3
export const HEAL_INTERVAL = 5          // idle mercs heal 1 hp every N ticks
export const MEDBAY_PER_HP = 10         // instant heal price per missing hp
export const REP_PER_TIER = 4           // rep needed per extra offer/candidate tier
